stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/iris.csv
    - src/prepare.py
    outs:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv

  train:
    cmd: python src/train.py
    deps:
    - data/X_train.csv
    - data/y_train.csv
    - src/train.py
    params:
    - train.n_estimators
    - train.max_depth
    outs:
    - model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/X_test.csv
    - data/y_test.csv
    - model.pkl
    - src/evaluate.py
    outs:
    - eval

plots:
- eval/plots/roc.json:
    title: ROC Curve
    x: fpr
    y: tpr
- eval/plots/prc.json:
    title: Precision-Recall Curve
    x: recall
    y: precision
- eval/plots/confusion.json:
    title: Confusion Matrix
    x: actual
    y: predicted
- live/plots/metrics:
    x: step
- dvclive/plots/metrics:
    x: step
- dvclive/plots/custom/confusion_matrix.json:
    template: confusion
    x: Actual
    y: Predicted
    title: Confusion Matrix
    x_label: Actual Label
    y_label: Predicted Label
metrics:
- live/metrics.json
- dvclive/metrics.json
